// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mes.ud.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION

#include "mes.ud.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace message {

    namespace {

        const ::google::protobuf::Descriptor *task_descriptor_ = NULL;
        const ::google::protobuf::internal::GeneratedMessageReflection *
                task_reflection_ = NULL;
        const ::google::protobuf::Descriptor *task_job_descriptor_ = NULL;
        const ::google::protobuf::internal::GeneratedMessageReflection *
                task_job_reflection_ = NULL;
        const ::google::protobuf::EnumDescriptor *task_type_descriptor_ = NULL;
        const ::google::protobuf::Descriptor *status_descriptor_ = NULL;
        const ::google::protobuf::internal::GeneratedMessageReflection *
                status_reflection_ = NULL;

    }  // namespace


    void protobuf_AssignDesc_mes_2eud_2eproto() {
        protobuf_AddDesc_mes_2eud_2eproto();
        const ::google::protobuf::FileDescriptor *file =
                ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
                        "mes.ud.proto");
        GOOGLE_CHECK(file != NULL);
        task_descriptor_ = file->message_type(0);
        static const int task_offsets_[4] = {
                GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(task, tcp_id_),
                GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(task, task_id_),
                GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(task, jobs_),
                GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(task, last_updated_),
        };
        task_reflection_ =
                new ::google::protobuf::internal::GeneratedMessageReflection(
                        task_descriptor_,
                        task::default_instance_,
                        task_offsets_,
                        GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(task, _has_bits_[0]),
                        GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(task, _unknown_fields_),
                        -1,
                        ::google::protobuf::DescriptorPool::generated_pool(),
                        ::google::protobuf::MessageFactory::generated_factory(),
                        sizeof(task));
        task_job_descriptor_ = task_descriptor_->nested_type(0);
        static const int task_job_offsets_[3] = {
                GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(task_job, job_type_),
                GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(task_job, file_path_),
                GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(task_job, description_),
        };
        task_job_reflection_ =
                new ::google::protobuf::internal::GeneratedMessageReflection(
                        task_job_descriptor_,
                        task_job::default_instance_,
                        task_job_offsets_,
                        GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(task_job, _has_bits_[0]),
                        GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(task_job, _unknown_fields_),
                        -1,
                        ::google::protobuf::DescriptorPool::generated_pool(),
                        ::google::protobuf::MessageFactory::generated_factory(),
                        sizeof(task_job));
        task_type_descriptor_ = task_descriptor_->enum_type(0);
        status_descriptor_ = file->message_type(1);
        static const int status_offsets_[6] = {
                GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(status, tcp_id_),
                GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(status, task_id_),
                GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(status, description_),
                GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(status, percentage_),
                GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(status, buffer_),
                GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(status, last_updated_),
        };
        status_reflection_ =
                new ::google::protobuf::internal::GeneratedMessageReflection(
                        status_descriptor_,
                        status::default_instance_,
                        status_offsets_,
                        GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(status, _has_bits_[0]),
                        GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(status, _unknown_fields_),
                        -1,
                        ::google::protobuf::DescriptorPool::generated_pool(),
                        ::google::protobuf::MessageFactory::generated_factory(),
                        sizeof(status));
    }

    namespace {

        GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);

        inline void protobuf_AssignDescriptorsOnce() {
            ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                                               &protobuf_AssignDesc_mes_2eud_2eproto);
        }

        void protobuf_RegisterTypes(const ::std::string &) {
            protobuf_AssignDescriptorsOnce();
            ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
                    task_descriptor_, &task::default_instance());
            ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
                    task_job_descriptor_, &task_job::default_instance());
            ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
                    status_descriptor_, &status::default_instance());
        }

    }  // namespace

    void protobuf_ShutdownFile_mes_2eud_2eproto() {
        delete task::default_instance_;
        delete task_reflection_;
        delete task_job::default_instance_;
        delete task_job_reflection_;
        delete status::default_instance_;
        delete status_reflection_;
    }

    void protobuf_AddDesc_mes_2eud_2eproto() {
        static bool already_here = false;
        if (already_here) return;
        already_here = true;
        GOOGLE_PROTOBUF_VERIFY_VERSION;

        ::message::protobuf_AddDesc_mes_2ebase_2eproto();
        ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
                "\n\014mes.ud.proto\022\007message\032\016mes.base.proto\""
                "\221\002\n\004task\022\037\n\006tcp_id\030\001 \002(\0132\017.message.tcp_i"
                "d\022\017\n\007task_id\030\002 \002(\005\022\037\n\004jobs\030\003 \003(\0132\021.messa"
                "ge.task.job\022(\n\014last_updated\030\004 \001(\0132\022.mess"
                "age.timestamp\032S\n\003job\022$\n\010job_type\030\001 \002(\0162\022"
                ".message.task.type\022\021\n\tfile_path\030\002 \001(\t\022\023\n"
                "\013description\030\003 \001(\t\"7\n\004type\022\r\n\tcalculate\020"
                "\000\022\021\n\rfile_transfer\020\001\022\r\n\tterminate\020\002\"\235\001\n\006"
                "status\022\037\n\006tcp_id\030\001 \002(\0132\017.message.tcp_id\022"
                "\017\n\007task_id\030\002 \002(\005\022\023\n\013description\030\003 \001(\t\022\022\n"
                "\npercentage\030\004 \001(\005\022\016\n\006buffer\030\005 \001(\t\022(\n\014las"
                "t_updated\030\006 \002(\0132\022.message.timestamp", 475);
        ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
                "mes.ud.proto", &protobuf_RegisterTypes);
        task::default_instance_ = new task();
        task_job::default_instance_ = new task_job();
        status::default_instance_ = new status();
        task::default_instance_->InitAsDefaultInstance();
        task_job::default_instance_->InitAsDefaultInstance();
        status::default_instance_->InitAsDefaultInstance();
        ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_mes_2eud_2eproto);
    }

// Force AddDescriptors() to be called at static initialization time.
    struct StaticDescriptorInitializer_mes_2eud_2eproto {
        StaticDescriptorInitializer_mes_2eud_2eproto() {
            protobuf_AddDesc_mes_2eud_2eproto();
        }
    } static_descriptor_initializer_mes_2eud_2eproto_;

// ===================================================================

    const ::google::protobuf::EnumDescriptor *task_type_descriptor() {
        protobuf_AssignDescriptorsOnce();
        return task_type_descriptor_;
    }

    bool task_type_IsValid(int value) {
        switch (value) {
            case 0:
            case 1:
            case 2:
                return true;
            default:
                return false;
        }
    }

#ifndef _MSC_VER
    const task_type task::calculate;
    const task_type task::file_transfer;
    const task_type task::terminate;
    const task_type task::type_MIN;
    const task_type task::type_MAX;
    const int task::type_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
    const int task_job::kJobTypeFieldNumber;
    const int task_job::kFilePathFieldNumber;
    const int task_job::kDescriptionFieldNumber;
#endif  // !_MSC_VER

    task_job::task_job()
            : ::google::protobuf::Message() {
        SharedCtor();
        // @@protoc_insertion_point(constructor:message.task.job)
    }

    void task_job::InitAsDefaultInstance() {
    }

    task_job::task_job(const task_job &from)
            : ::google::protobuf::Message() {
        SharedCtor();
        MergeFrom(from);
        // @@protoc_insertion_point(copy_constructor:message.task.job)
    }

    void task_job::SharedCtor() {
        ::google::protobuf::internal::GetEmptyString();
        _cached_size_ = 0;
        job_type_ = 0;
        file_path_ = const_cast< ::std::string *>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        description_ = const_cast< ::std::string *>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        ::memset(_has_bits_, 0, sizeof(_has_bits_));
    }

    task_job::~task_job() {
        // @@protoc_insertion_point(destructor:message.task.job)
        SharedDtor();
    }

    void task_job::SharedDtor() {
        if (file_path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
            delete file_path_;
        }
        if (description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
            delete description_;
        }
        if (this != default_instance_) {
        }
    }

    void task_job::SetCachedSize(int size) const {
        GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
        _cached_size_ = size;
        GOOGLE_SAFE_CONCURRENT_WRITES_END();
    }

    const ::google::protobuf::Descriptor *task_job::descriptor() {
        protobuf_AssignDescriptorsOnce();
        return task_job_descriptor_;
    }

    const task_job &task_job::default_instance() {
        if (default_instance_ == NULL) protobuf_AddDesc_mes_2eud_2eproto();
        return *default_instance_;
    }

    task_job *task_job::default_instance_ = NULL;

    task_job *task_job::New() const {
        return new task_job;
    }

    void task_job::Clear() {
        if (_has_bits_[0 / 32] & 7) {
            job_type_ = 0;
            if (has_file_path()) {
                if (file_path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
                    file_path_->clear();
                }
            }
            if (has_description()) {
                if (description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
                    description_->clear();
                }
            }
        }
        ::memset(_has_bits_, 0, sizeof(_has_bits_));
        mutable_unknown_fields()->Clear();
    }

    bool task_job::MergePartialFromCodedStream(
            ::google::protobuf::io::CodedInputStream *input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
        ::google::protobuf::uint32 tag;
        // @@protoc_insertion_point(parse_start:message.task.job)
        for (;;) {
            ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
            tag = p.first;
            if (!p.second) goto handle_unusual;
            switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
                // required .message.task.type job_type = 1;
                case 1: {
                    if (tag == 8) {
                        int value;
                        DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                                int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                                input, &value)));
                        if (::message::task_type_IsValid(value)) {
                            set_job_type(static_cast< ::message::task_type >(value));
                        } else {
                            mutable_unknown_fields()->AddVarint(1, value);
                        }
                    } else {
                        goto handle_unusual;
                    }
                    if (input->ExpectTag(18)) goto parse_file_path;
                    break;
                }

                    // optional string file_path = 2;
                case 2: {
                    if (tag == 18) {
                        parse_file_path:
                        DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                                input, this->mutable_file_path()));
                        ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
                                this->file_path().data(), this->file_path().length(),
                                ::google::protobuf::internal::WireFormat::PARSE,
                                "file_path");
                    } else {
                        goto handle_unusual;
                    }
                    if (input->ExpectTag(26)) goto parse_description;
                    break;
                }

                    // optional string description = 3;
                case 3: {
                    if (tag == 26) {
                        parse_description:
                        DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                                input, this->mutable_description()));
                        ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
                                this->description().data(), this->description().length(),
                                ::google::protobuf::internal::WireFormat::PARSE,
                                "description");
                    } else {
                        goto handle_unusual;
                    }
                    if (input->ExpectAtEnd()) goto success;
                    break;
                }

                default: {
                    handle_unusual:
                    if (tag == 0 ||
                        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
                        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
                        goto success;
                    }
                    DO_(::google::protobuf::internal::WireFormat::SkipField(
                            input, tag, mutable_unknown_fields()));
                    break;
                }
            }
        }
        success:
        // @@protoc_insertion_point(parse_success:message.task.job)
        return true;
        failure:
        // @@protoc_insertion_point(parse_failure:message.task.job)
        return false;
#undef DO_
    }

    void task_job::SerializeWithCachedSizes(
            ::google::protobuf::io::CodedOutputStream *output) const {
        // @@protoc_insertion_point(serialize_start:message.task.job)
        // required .message.task.type job_type = 1;
        if (has_job_type()) {
            ::google::protobuf::internal::WireFormatLite::WriteEnum(
                    1, this->job_type(), output);
        }

        // optional string file_path = 2;
        if (has_file_path()) {
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
                    this->file_path().data(), this->file_path().length(),
                    ::google::protobuf::internal::WireFormat::SERIALIZE,
                    "file_path");
            ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
                    2, this->file_path(), output);
        }

        // optional string description = 3;
        if (has_description()) {
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
                    this->description().data(), this->description().length(),
                    ::google::protobuf::internal::WireFormat::SERIALIZE,
                    "description");
            ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
                    3, this->description(), output);
        }

        if (!unknown_fields().empty()) {
            ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
                    unknown_fields(), output);
        }
        // @@protoc_insertion_point(serialize_end:message.task.job)
    }

    ::google::protobuf::uint8 *task_job::SerializeWithCachedSizesToArray(
            ::google::protobuf::uint8 *target) const {
        // @@protoc_insertion_point(serialize_to_array_start:message.task.job)
        // required .message.task.type job_type = 1;
        if (has_job_type()) {
            target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
                    1, this->job_type(), target);
        }

        // optional string file_path = 2;
        if (has_file_path()) {
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
                    this->file_path().data(), this->file_path().length(),
                    ::google::protobuf::internal::WireFormat::SERIALIZE,
                    "file_path");
            target =
                    ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
                            2, this->file_path(), target);
        }

        // optional string description = 3;
        if (has_description()) {
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
                    this->description().data(), this->description().length(),
                    ::google::protobuf::internal::WireFormat::SERIALIZE,
                    "description");
            target =
                    ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
                            3, this->description(), target);
        }

        if (!unknown_fields().empty()) {
            target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
                    unknown_fields(), target);
        }
        // @@protoc_insertion_point(serialize_to_array_end:message.task.job)
        return target;
    }

    int task_job::ByteSize() const {
        int total_size = 0;

        if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
            // required .message.task.type job_type = 1;
            if (has_job_type()) {
                total_size += 1 +
                              ::google::protobuf::internal::WireFormatLite::EnumSize(this->job_type());
            }

            // optional string file_path = 2;
            if (has_file_path()) {
                total_size += 1 +
                              ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->file_path());
            }

            // optional string description = 3;
            if (has_description()) {
                total_size += 1 +
                              ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->description());
            }

        }
        if (!unknown_fields().empty()) {
            total_size +=
                    ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
                            unknown_fields());
        }
        GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
        _cached_size_ = total_size;
        GOOGLE_SAFE_CONCURRENT_WRITES_END();
        return total_size;
    }

    void task_job::MergeFrom(const ::google::protobuf::Message &from) {
        GOOGLE_CHECK_NE(&from, this);
        const task_job *source =
                ::google::protobuf::internal::dynamic_cast_if_available<const task_job *>(
                        &from);
        if (source == NULL) {
            ::google::protobuf::internal::ReflectionOps::Merge(from, this);
        } else {
            MergeFrom(*source);
        }
    }

    void task_job::MergeFrom(const task_job &from) {
        GOOGLE_CHECK_NE(&from, this);
        if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
            if (from.has_job_type()) {
                set_job_type(from.job_type());
            }
            if (from.has_file_path()) {
                set_file_path(from.file_path());
            }
            if (from.has_description()) {
                set_description(from.description());
            }
        }
        mutable_unknown_fields()->MergeFrom(from.unknown_fields());
    }

    void task_job::CopyFrom(const ::google::protobuf::Message &from) {
        if (&from == this) return;
        Clear();
        MergeFrom(from);
    }

    void task_job::CopyFrom(const task_job &from) {
        if (&from == this) return;
        Clear();
        MergeFrom(from);
    }

    bool task_job::IsInitialized() const {
        if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

        return true;
    }

    void task_job::Swap(task_job *other) {
        if (other != this) {
            std::swap(job_type_, other->job_type_);
            std::swap(file_path_, other->file_path_);
            std::swap(description_, other->description_);
            std::swap(_has_bits_[0], other->_has_bits_[0]);
            _unknown_fields_.Swap(&other->_unknown_fields_);
            std::swap(_cached_size_, other->_cached_size_);
        }
    }

    ::google::protobuf::Metadata task_job::GetMetadata() const {
        protobuf_AssignDescriptorsOnce();
        ::google::protobuf::Metadata metadata;
        metadata.descriptor = task_job_descriptor_;
        metadata.reflection = task_job_reflection_;
        return metadata;
    }


// -------------------------------------------------------------------

#ifndef _MSC_VER
    const int task::kTcpIdFieldNumber;
    const int task::kTaskIdFieldNumber;
    const int task::kJobsFieldNumber;
    const int task::kLastUpdatedFieldNumber;
#endif  // !_MSC_VER

    task::task()
            : ::google::protobuf::Message() {
        SharedCtor();
        // @@protoc_insertion_point(constructor:message.task)
    }

    void task::InitAsDefaultInstance() {
        tcp_id_ = const_cast< ::message::tcp_id *>(&::message::tcp_id::default_instance());
        last_updated_ = const_cast< ::message::timestamp *>(&::message::timestamp::default_instance());
    }

    task::task(const task &from)
            : ::google::protobuf::Message() {
        SharedCtor();
        MergeFrom(from);
        // @@protoc_insertion_point(copy_constructor:message.task)
    }

    void task::SharedCtor() {
        _cached_size_ = 0;
        tcp_id_ = NULL;
        task_id_ = 0;
        last_updated_ = NULL;
        ::memset(_has_bits_, 0, sizeof(_has_bits_));
    }

    task::~task() {
        // @@protoc_insertion_point(destructor:message.task)
        SharedDtor();
    }

    void task::SharedDtor() {
        if (this != default_instance_) {
            delete tcp_id_;
            delete last_updated_;
        }
    }

    void task::SetCachedSize(int size) const {
        GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
        _cached_size_ = size;
        GOOGLE_SAFE_CONCURRENT_WRITES_END();
    }

    const ::google::protobuf::Descriptor *task::descriptor() {
        protobuf_AssignDescriptorsOnce();
        return task_descriptor_;
    }

    const task &task::default_instance() {
        if (default_instance_ == NULL) protobuf_AddDesc_mes_2eud_2eproto();
        return *default_instance_;
    }

    task *task::default_instance_ = NULL;

    task *task::New() const {
        return new task;
    }

    void task::Clear() {
        if (_has_bits_[0 / 32] & 11) {
            if (has_tcp_id()) {
                if (tcp_id_ != NULL) tcp_id_->::message::tcp_id::Clear();
            }
            task_id_ = 0;
            if (has_last_updated()) {
                if (last_updated_ != NULL) last_updated_->::message::timestamp::Clear();
            }
        }
        jobs_.Clear();
        ::memset(_has_bits_, 0, sizeof(_has_bits_));
        mutable_unknown_fields()->Clear();
    }

    bool task::MergePartialFromCodedStream(
            ::google::protobuf::io::CodedInputStream *input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
        ::google::protobuf::uint32 tag;
        // @@protoc_insertion_point(parse_start:message.task)
        for (;;) {
            ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
            tag = p.first;
            if (!p.second) goto handle_unusual;
            switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
                // required .message.tcp_id tcp_id = 1;
                case 1: {
                    if (tag == 10) {
                        DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                                input, mutable_tcp_id()));
                    } else {
                        goto handle_unusual;
                    }
                    if (input->ExpectTag(16)) goto parse_task_id;
                    break;
                }

                    // required int32 task_id = 2;
                case 2: {
                    if (tag == 16) {
                        parse_task_id:
                        DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                                ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                                input, &task_id_)));
                        set_has_task_id();
                    } else {
                        goto handle_unusual;
                    }
                    if (input->ExpectTag(26)) goto parse_jobs;
                    break;
                }

                    // repeated .message.task.job jobs = 3;
                case 3: {
                    if (tag == 26) {
                        parse_jobs:
                        DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                                input, add_jobs()));
                    } else {
                        goto handle_unusual;
                    }
                    if (input->ExpectTag(26)) goto parse_jobs;
                    if (input->ExpectTag(34)) goto parse_last_updated;
                    break;
                }

                    // optional .message.timestamp last_updated = 4;
                case 4: {
                    if (tag == 34) {
                        parse_last_updated:
                        DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                                input, mutable_last_updated()));
                    } else {
                        goto handle_unusual;
                    }
                    if (input->ExpectAtEnd()) goto success;
                    break;
                }

                default: {
                    handle_unusual:
                    if (tag == 0 ||
                        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
                        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
                        goto success;
                    }
                    DO_(::google::protobuf::internal::WireFormat::SkipField(
                            input, tag, mutable_unknown_fields()));
                    break;
                }
            }
        }
        success:
        // @@protoc_insertion_point(parse_success:message.task)
        return true;
        failure:
        // @@protoc_insertion_point(parse_failure:message.task)
        return false;
#undef DO_
    }

    void task::SerializeWithCachedSizes(
            ::google::protobuf::io::CodedOutputStream *output) const {
        // @@protoc_insertion_point(serialize_start:message.task)
        // required .message.tcp_id tcp_id = 1;
        if (has_tcp_id()) {
            ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
                    1, this->tcp_id(), output);
        }

        // required int32 task_id = 2;
        if (has_task_id()) {
            ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->task_id(), output);
        }

        // repeated .message.task.job jobs = 3;
        for (int i = 0; i < this->jobs_size(); i++) {
            ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
                    3, this->jobs(i), output);
        }

        // optional .message.timestamp last_updated = 4;
        if (has_last_updated()) {
            ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
                    4, this->last_updated(), output);
        }

        if (!unknown_fields().empty()) {
            ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
                    unknown_fields(), output);
        }
        // @@protoc_insertion_point(serialize_end:message.task)
    }

    ::google::protobuf::uint8 *task::SerializeWithCachedSizesToArray(
            ::google::protobuf::uint8 *target) const {
        // @@protoc_insertion_point(serialize_to_array_start:message.task)
        // required .message.tcp_id tcp_id = 1;
        if (has_tcp_id()) {
            target = ::google::protobuf::internal::WireFormatLite::
            WriteMessageNoVirtualToArray(
                    1, this->tcp_id(), target);
        }

        // required int32 task_id = 2;
        if (has_task_id()) {
            target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->task_id(), target);
        }

        // repeated .message.task.job jobs = 3;
        for (int i = 0; i < this->jobs_size(); i++) {
            target = ::google::protobuf::internal::WireFormatLite::
            WriteMessageNoVirtualToArray(
                    3, this->jobs(i), target);
        }

        // optional .message.timestamp last_updated = 4;
        if (has_last_updated()) {
            target = ::google::protobuf::internal::WireFormatLite::
            WriteMessageNoVirtualToArray(
                    4, this->last_updated(), target);
        }

        if (!unknown_fields().empty()) {
            target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
                    unknown_fields(), target);
        }
        // @@protoc_insertion_point(serialize_to_array_end:message.task)
        return target;
    }

    int task::ByteSize() const {
        int total_size = 0;

        if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
            // required .message.tcp_id tcp_id = 1;
            if (has_tcp_id()) {
                total_size += 1 +
                              ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
                                      this->tcp_id());
            }

            // required int32 task_id = 2;
            if (has_task_id()) {
                total_size += 1 +
                              ::google::protobuf::internal::WireFormatLite::Int32Size(
                                      this->task_id());
            }

            // optional .message.timestamp last_updated = 4;
            if (has_last_updated()) {
                total_size += 1 +
                              ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
                                      this->last_updated());
            }

        }
        // repeated .message.task.job jobs = 3;
        total_size += 1 * this->jobs_size();
        for (int i = 0; i < this->jobs_size(); i++) {
            total_size +=
                    ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
                            this->jobs(i));
        }

        if (!unknown_fields().empty()) {
            total_size +=
                    ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
                            unknown_fields());
        }
        GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
        _cached_size_ = total_size;
        GOOGLE_SAFE_CONCURRENT_WRITES_END();
        return total_size;
    }

    void task::MergeFrom(const ::google::protobuf::Message &from) {
        GOOGLE_CHECK_NE(&from, this);
        const task *source =
                ::google::protobuf::internal::dynamic_cast_if_available<const task *>(
                        &from);
        if (source == NULL) {
            ::google::protobuf::internal::ReflectionOps::Merge(from, this);
        } else {
            MergeFrom(*source);
        }
    }

    void task::MergeFrom(const task &from) {
        GOOGLE_CHECK_NE(&from, this);
        jobs_.MergeFrom(from.jobs_);
        if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
            if (from.has_tcp_id()) {
                mutable_tcp_id()->::message::tcp_id::MergeFrom(from.tcp_id());
            }
            if (from.has_task_id()) {
                set_task_id(from.task_id());
            }
            if (from.has_last_updated()) {
                mutable_last_updated()->::message::timestamp::MergeFrom(from.last_updated());
            }
        }
        mutable_unknown_fields()->MergeFrom(from.unknown_fields());
    }

    void task::CopyFrom(const ::google::protobuf::Message &from) {
        if (&from == this) return;
        Clear();
        MergeFrom(from);
    }

    void task::CopyFrom(const task &from) {
        if (&from == this) return;
        Clear();
        MergeFrom(from);
    }

    bool task::IsInitialized() const {
        if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

        if (has_tcp_id()) {
            if (!this->tcp_id().IsInitialized()) return false;
        }
        if (!::google::protobuf::internal::AllAreInitialized(this->jobs())) return false;
        if (has_last_updated()) {
            if (!this->last_updated().IsInitialized()) return false;
        }
        return true;
    }

    void task::Swap(task *other) {
        if (other != this) {
            std::swap(tcp_id_, other->tcp_id_);
            std::swap(task_id_, other->task_id_);
            jobs_.Swap(&other->jobs_);
            std::swap(last_updated_, other->last_updated_);
            std::swap(_has_bits_[0], other->_has_bits_[0]);
            _unknown_fields_.Swap(&other->_unknown_fields_);
            std::swap(_cached_size_, other->_cached_size_);
        }
    }

    ::google::protobuf::Metadata task::GetMetadata() const {
        protobuf_AssignDescriptorsOnce();
        ::google::protobuf::Metadata metadata;
        metadata.descriptor = task_descriptor_;
        metadata.reflection = task_reflection_;
        return metadata;
    }


// ===================================================================

#ifndef _MSC_VER
    const int status::kTcpIdFieldNumber;
    const int status::kTaskIdFieldNumber;
    const int status::kDescriptionFieldNumber;
    const int status::kPercentageFieldNumber;
    const int status::kBufferFieldNumber;
    const int status::kLastUpdatedFieldNumber;
#endif  // !_MSC_VER

    status::status()
            : ::google::protobuf::Message() {
        SharedCtor();
        // @@protoc_insertion_point(constructor:message.status)
    }

    void status::InitAsDefaultInstance() {
        tcp_id_ = const_cast< ::message::tcp_id *>(&::message::tcp_id::default_instance());
        last_updated_ = const_cast< ::message::timestamp *>(&::message::timestamp::default_instance());
    }

    status::status(const status &from)
            : ::google::protobuf::Message() {
        SharedCtor();
        MergeFrom(from);
        // @@protoc_insertion_point(copy_constructor:message.status)
    }

    void status::SharedCtor() {
        ::google::protobuf::internal::GetEmptyString();
        _cached_size_ = 0;
        tcp_id_ = NULL;
        task_id_ = 0;
        description_ = const_cast< ::std::string *>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        percentage_ = 0;
        buffer_ = const_cast< ::std::string *>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
        last_updated_ = NULL;
        ::memset(_has_bits_, 0, sizeof(_has_bits_));
    }

    status::~status() {
        // @@protoc_insertion_point(destructor:message.status)
        SharedDtor();
    }

    void status::SharedDtor() {
        if (description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
            delete description_;
        }
        if (buffer_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
            delete buffer_;
        }
        if (this != default_instance_) {
            delete tcp_id_;
            delete last_updated_;
        }
    }

    void status::SetCachedSize(int size) const {
        GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
        _cached_size_ = size;
        GOOGLE_SAFE_CONCURRENT_WRITES_END();
    }

    const ::google::protobuf::Descriptor *status::descriptor() {
        protobuf_AssignDescriptorsOnce();
        return status_descriptor_;
    }

    const status &status::default_instance() {
        if (default_instance_ == NULL) protobuf_AddDesc_mes_2eud_2eproto();
        return *default_instance_;
    }

    status *status::default_instance_ = NULL;

    status *status::New() const {
        return new status;
    }

    void status::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<status*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

        if (_has_bits_[0 / 32] & 63) {
            ZR_(task_id_, percentage_);
            if (has_tcp_id()) {
                if (tcp_id_ != NULL) tcp_id_->::message::tcp_id::Clear();
            }
            if (has_description()) {
                if (description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
                    description_->clear();
                }
            }
            if (has_buffer()) {
                if (buffer_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
                    buffer_->clear();
                }
            }
            if (has_last_updated()) {
                if (last_updated_ != NULL) last_updated_->::message::timestamp::Clear();
            }
        }

#undef OFFSET_OF_FIELD_
#undef ZR_

        ::memset(_has_bits_, 0, sizeof(_has_bits_));
        mutable_unknown_fields()->Clear();
    }

    bool status::MergePartialFromCodedStream(
            ::google::protobuf::io::CodedInputStream *input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
        ::google::protobuf::uint32 tag;
        // @@protoc_insertion_point(parse_start:message.status)
        for (;;) {
            ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
            tag = p.first;
            if (!p.second) goto handle_unusual;
            switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
                // required .message.tcp_id tcp_id = 1;
                case 1: {
                    if (tag == 10) {
                        DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                                input, mutable_tcp_id()));
                    } else {
                        goto handle_unusual;
                    }
                    if (input->ExpectTag(16)) goto parse_task_id;
                    break;
                }

                    // required int32 task_id = 2;
                case 2: {
                    if (tag == 16) {
                        parse_task_id:
                        DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                                ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                                input, &task_id_)));
                        set_has_task_id();
                    } else {
                        goto handle_unusual;
                    }
                    if (input->ExpectTag(26)) goto parse_description;
                    break;
                }

                    // optional string description = 3;
                case 3: {
                    if (tag == 26) {
                        parse_description:
                        DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                                input, this->mutable_description()));
                        ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
                                this->description().data(), this->description().length(),
                                ::google::protobuf::internal::WireFormat::PARSE,
                                "description");
                    } else {
                        goto handle_unusual;
                    }
                    if (input->ExpectTag(32)) goto parse_percentage;
                    break;
                }

                    // optional int32 percentage = 4;
                case 4: {
                    if (tag == 32) {
                        parse_percentage:
                        DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                                ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                                input, &percentage_)));
                        set_has_percentage();
                    } else {
                        goto handle_unusual;
                    }
                    if (input->ExpectTag(42)) goto parse_buffer;
                    break;
                }

                    // optional string buffer = 5;
                case 5: {
                    if (tag == 42) {
                        parse_buffer:
                        DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                                input, this->mutable_buffer()));
                        ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
                                this->buffer().data(), this->buffer().length(),
                                ::google::protobuf::internal::WireFormat::PARSE,
                                "buffer");
                    } else {
                        goto handle_unusual;
                    }
                    if (input->ExpectTag(50)) goto parse_last_updated;
                    break;
                }

                    // required .message.timestamp last_updated = 6;
                case 6: {
                    if (tag == 50) {
                        parse_last_updated:
                        DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                                input, mutable_last_updated()));
                    } else {
                        goto handle_unusual;
                    }
                    if (input->ExpectAtEnd()) goto success;
                    break;
                }

                default: {
                    handle_unusual:
                    if (tag == 0 ||
                        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
                        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
                        goto success;
                    }
                    DO_(::google::protobuf::internal::WireFormat::SkipField(
                            input, tag, mutable_unknown_fields()));
                    break;
                }
            }
        }
        success:
        // @@protoc_insertion_point(parse_success:message.status)
        return true;
        failure:
        // @@protoc_insertion_point(parse_failure:message.status)
        return false;
#undef DO_
    }

    void status::SerializeWithCachedSizes(
            ::google::protobuf::io::CodedOutputStream *output) const {
        // @@protoc_insertion_point(serialize_start:message.status)
        // required .message.tcp_id tcp_id = 1;
        if (has_tcp_id()) {
            ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
                    1, this->tcp_id(), output);
        }

        // required int32 task_id = 2;
        if (has_task_id()) {
            ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->task_id(), output);
        }

        // optional string description = 3;
        if (has_description()) {
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
                    this->description().data(), this->description().length(),
                    ::google::protobuf::internal::WireFormat::SERIALIZE,
                    "description");
            ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
                    3, this->description(), output);
        }

        // optional int32 percentage = 4;
        if (has_percentage()) {
            ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->percentage(), output);
        }

        // optional string buffer = 5;
        if (has_buffer()) {
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
                    this->buffer().data(), this->buffer().length(),
                    ::google::protobuf::internal::WireFormat::SERIALIZE,
                    "buffer");
            ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
                    5, this->buffer(), output);
        }

        // required .message.timestamp last_updated = 6;
        if (has_last_updated()) {
            ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
                    6, this->last_updated(), output);
        }

        if (!unknown_fields().empty()) {
            ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
                    unknown_fields(), output);
        }
        // @@protoc_insertion_point(serialize_end:message.status)
    }

    ::google::protobuf::uint8 *status::SerializeWithCachedSizesToArray(
            ::google::protobuf::uint8 *target) const {
        // @@protoc_insertion_point(serialize_to_array_start:message.status)
        // required .message.tcp_id tcp_id = 1;
        if (has_tcp_id()) {
            target = ::google::protobuf::internal::WireFormatLite::
            WriteMessageNoVirtualToArray(
                    1, this->tcp_id(), target);
        }

        // required int32 task_id = 2;
        if (has_task_id()) {
            target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->task_id(), target);
        }

        // optional string description = 3;
        if (has_description()) {
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
                    this->description().data(), this->description().length(),
                    ::google::protobuf::internal::WireFormat::SERIALIZE,
                    "description");
            target =
                    ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
                            3, this->description(), target);
        }

        // optional int32 percentage = 4;
        if (has_percentage()) {
            target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->percentage(), target);
        }

        // optional string buffer = 5;
        if (has_buffer()) {
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
                    this->buffer().data(), this->buffer().length(),
                    ::google::protobuf::internal::WireFormat::SERIALIZE,
                    "buffer");
            target =
                    ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
                            5, this->buffer(), target);
        }

        // required .message.timestamp last_updated = 6;
        if (has_last_updated()) {
            target = ::google::protobuf::internal::WireFormatLite::
            WriteMessageNoVirtualToArray(
                    6, this->last_updated(), target);
        }

        if (!unknown_fields().empty()) {
            target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
                    unknown_fields(), target);
        }
        // @@protoc_insertion_point(serialize_to_array_end:message.status)
        return target;
    }

    int status::ByteSize() const {
        int total_size = 0;

        if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
            // required .message.tcp_id tcp_id = 1;
            if (has_tcp_id()) {
                total_size += 1 +
                              ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
                                      this->tcp_id());
            }

            // required int32 task_id = 2;
            if (has_task_id()) {
                total_size += 1 +
                              ::google::protobuf::internal::WireFormatLite::Int32Size(
                                      this->task_id());
            }

            // optional string description = 3;
            if (has_description()) {
                total_size += 1 +
                              ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->description());
            }

            // optional int32 percentage = 4;
            if (has_percentage()) {
                total_size += 1 +
                              ::google::protobuf::internal::WireFormatLite::Int32Size(
                                      this->percentage());
            }

            // optional string buffer = 5;
            if (has_buffer()) {
                total_size += 1 +
                              ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->buffer());
            }

            // required .message.timestamp last_updated = 6;
            if (has_last_updated()) {
                total_size += 1 +
                              ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
                                      this->last_updated());
            }

        }
        if (!unknown_fields().empty()) {
            total_size +=
                    ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
                            unknown_fields());
        }
        GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
        _cached_size_ = total_size;
        GOOGLE_SAFE_CONCURRENT_WRITES_END();
        return total_size;
    }

    void status::MergeFrom(const ::google::protobuf::Message &from) {
        GOOGLE_CHECK_NE(&from, this);
        const status *source =
                ::google::protobuf::internal::dynamic_cast_if_available<const status *>(
                        &from);
        if (source == NULL) {
            ::google::protobuf::internal::ReflectionOps::Merge(from, this);
        } else {
            MergeFrom(*source);
        }
    }

    void status::MergeFrom(const status &from) {
        GOOGLE_CHECK_NE(&from, this);
        if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
            if (from.has_tcp_id()) {
                mutable_tcp_id()->::message::tcp_id::MergeFrom(from.tcp_id());
            }
            if (from.has_task_id()) {
                set_task_id(from.task_id());
            }
            if (from.has_description()) {
                set_description(from.description());
            }
            if (from.has_percentage()) {
                set_percentage(from.percentage());
            }
            if (from.has_buffer()) {
                set_buffer(from.buffer());
            }
            if (from.has_last_updated()) {
                mutable_last_updated()->::message::timestamp::MergeFrom(from.last_updated());
            }
        }
        mutable_unknown_fields()->MergeFrom(from.unknown_fields());
    }

    void status::CopyFrom(const ::google::protobuf::Message &from) {
        if (&from == this) return;
        Clear();
        MergeFrom(from);
    }

    void status::CopyFrom(const status &from) {
        if (&from == this) return;
        Clear();
        MergeFrom(from);
    }

    bool status::IsInitialized() const {
        if ((_has_bits_[0] & 0x00000023) != 0x00000023) return false;

        if (has_tcp_id()) {
            if (!this->tcp_id().IsInitialized()) return false;
        }
        if (has_last_updated()) {
            if (!this->last_updated().IsInitialized()) return false;
        }
        return true;
    }

    void status::Swap(status *other) {
        if (other != this) {
            std::swap(tcp_id_, other->tcp_id_);
            std::swap(task_id_, other->task_id_);
            std::swap(description_, other->description_);
            std::swap(percentage_, other->percentage_);
            std::swap(buffer_, other->buffer_);
            std::swap(last_updated_, other->last_updated_);
            std::swap(_has_bits_[0], other->_has_bits_[0]);
            _unknown_fields_.Swap(&other->_unknown_fields_);
            std::swap(_cached_size_, other->_cached_size_);
        }
    }

    ::google::protobuf::Metadata status::GetMetadata() const {
        protobuf_AssignDescriptorsOnce();
        ::google::protobuf::Metadata metadata;
        metadata.descriptor = status_descriptor_;
        metadata.reflection = status_reflection_;
        return metadata;
    }


// @@protoc_insertion_point(namespace_scope)

}  // namespace message

// @@protoc_insertion_point(global_scope)
